### ISSUE TITLE
#US04 Como usuario, quiero recibir la confirmacion de pago.

### ISSUE THREAD

**Issue by vstecnic** [TravelDreams2024/ISPC2024#18]

**Comment by rominarg** [comment]
Descripción:
Como usuario de la plataforma, deseo recibir una confirmación inmediata de que mis pagos se han procesado correctamente y han sido registrados en mi cuenta. Esta confirmación es crucial para mantener la transparencia y la confianza en el sistema de pago de la plataforma.

Criterios de Aceptación:

Cuando realice un pago, debo recibir una notificación o mensaje que confirme que el pago ha sido recibido.
La confirmación debe incluir detalles específicos del pago, como el monto, la fecha y la descripción de la transacción.
Debo poder acceder fácilmente a un historial de pagos para verificar el registro de todas las transacciones anteriores.
En caso de algún problema o error en el proceso de pago, debo recibir una notificación clara que indique el problema y los pasos a seguir para resolverlo.
