### ISSUE TITLE
#US 09 Como usuario quiero tener una seccion de Registro de usuario y de inicio de sesion

### ISSUE THREAD

**Issue by MaxiCantarino** [TravelDreams2024/ISPC2024#4]

**Comment by ariel957** [comment]
Descripción:
Como usuario de la plataforma, deseo poder registrarme como usuario, para acceder a funcionalidades exclusivas, gestionar mis reservas y recibir actualizaciones personalizadas.

Criterios de Aceptación:
-Acceso al Formulario de Registro: Debe haber un enlace o botón claramente visible para iniciar el proceso de registro.
-Facilidad de Registro: El formulario de registro debe ser sencillo, pidiendo solo la información esencial para crear una cuenta (como nombre, correo electrónico y contraseña).
-Confirmación de Registro: Tras completar el registro, debo recibir una confirmación por correo electrónico que verifique mi cuenta.
-Acceso Inmediato: Una vez confirmada la cuenta, debo poder iniciar sesión y acceder a las funciones de usuario sin demoras.
-Protección de Datos: La plataforma debe asegurar que mis datos personales están protegidos y que cumple con las normativas de privacidad.
