### ISSUE TITLE
#US10 Como usuario quiero tener alternativas de Metodo de pago

### ISSUE THREAD

**Issue by MaxiCantarino** [TravelDreams2024/ISPC2024#5]

**Comment by ariel957** [comment]
Descripción: Como usuario de la plataforma TravelDreams2024, deseo tener opciones de pago seguras y confiables,
Para poder realizar mis pagos de reservas de manera eficiente y sin preocupaciones.

Criterios de Aceptación:

-Variedad de Opciones de Pago: Debo poder elegir entre múltiples métodos de pago, incluyendo tarjetas de crédito, débito, PayPal y otros sistemas de pago en línea.
-Proceso de Pago Intuitivo: El proceso para realizar un pago debe ser claro y fácil de seguir, sin pasos innecesarios que puedan causar confusión.
-Seguridad en el Pago: La plataforma debe garantizar la seguridad de mis datos financieros mediante el uso de tecnología de encriptación y cumplimiento de estándares de seguridad.
-Confirmación de Pago: Después de realizar un pago, debo recibir una confirmación inmediata, ya sea a través de un mensaje en la plataforma o por correo electrónico, que detalle la transacción realizada.
-Soporte para Problemas de Pago: En caso de que surja algún problema con mi pago, debo tener acceso a soporte al cliente para resolver el asunto de manera oportuna.
